apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/bazarr-config
    type: DirectoryOrCreate
