apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-nfs
spec:
  storageClassName: books-nfs
  volumeMode: Filesystem
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.41
    path: "/mnt/storage/nfs/books"
  mountOptions:
    - mountvers=4
    - nolock
