apiVersion: v1
kind: PersistentVolume
metadata:
  name: next-cloud
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /media/data/k3s/next-cloud
    type: DirectoryOrCreate
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - nas
