apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  storageClassName: nextcloud-nfs
  volumeMode: Filesystem
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.41
    path: "/mnt/storage/nfs/nextcloud-data"
  mountOptions:
    - mountvers=4
    - nolock

