apiVersion: v1
kind: PersistentVolume
metadata:
  name: next-cloud-src
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/next-cloud-src
    type: DirectoryOrCreate
