apiVersion: v1
kind: PersistentVolume
metadata:
  name: next-cloud-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/next-cloud-db
    type: DirectoryOrCreate
