apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-hdd
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /media/hdd/k3s/plex-media
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nas
