apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/plex-transcode
    type: DirectoryOrCreate
