apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/plex-data
    type: DirectoryOrCreate
