apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-nfs
spec:
  storageClassName: nfs-plex
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.41
    path: "/mnt/storage/nfs/plexmedia"
  mountOptions:
    - mountvers=4
    - nolock

