apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/plex-config
    type: DirectoryOrCreate
