apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-download2-nfs
spec:
  storageClassName: nfs-ssd
  volumeMode: Filesystem
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.41
    path: "/mnt/ultrafaststorage/nfs"
  mountOptions:
    - mountvers=4
    - nolock
