apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-download
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /mnt/ssd0/nfs
    type: DirectoryOrCreate
