apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-vpn
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/qbittorrent-vpn
    type: DirectoryOrCreate
