apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-download-hdd
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  hostPath:
    path: >-
      /media/hdd/k3s/qbittorrent-download
    type: DirectoryOrCreate
