apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/radarr-config
    type: DirectoryOrCreate
