apiVersion: v1
kind: PersistentVolume
metadata:
  name: render-minecraft-server
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: minecraft-server
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/render-minecraft-server
    type: DirectoryOrCreate
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - xps-13
