apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud-nfs
  namespace: default
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: default
  set:
    nfs.server: 192.168.1.41
    nfs.path: /mnt/storage/nfs/nextcloud-data
    storageClass.name: nextcloud-nfs
