# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.containo.us/middleware_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-discourse
  namespace: {{ .Release.Namespace | quote }}
spec:
  redirectRegex:
    regex: "^https?://discourse\\.kub\\.home\\.ashudev\\.com/(.*)"
    replacement: "https://forum.ashuvidz.com/$1"
    permanent: true
