apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-discourse
  namespace: {{ .Release.Namespace | quote }}
spec:
  redirectRegex:
    regex: "^https?://discourse\\.kub\\.home\\.ashudev\\.com/(.*)"
    replacement: "https://forum.ashuvidz.com/$1"
    permanent: true
