apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=fireflyiii/core:version-^6.x, db=postgres:^14.x-0, cron=alpine:^3.x
    argocd-image-updater.argoproj.io/app.helm.image-name: app.image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag
    argocd-image-updater.argoproj.io/db.helm.image-name: db.image.repository
    argocd-image-updater.argoproj.io/db.helm.image-tag: db.image.tag
    argocd-image-updater.argoproj.io/db.allow-tags: 'regexp:^(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?-alpine.*'
    argocd-image-updater.argoproj.io/cron.helm.image-name: cron.image.repository
    argocd-image-updater.argoproj.io/cron.helm.image-tag: cron.image.tag
  name: firefly
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: firefly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
    targetRevision: develop
    path: cluster/helm/firefly

