apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacd.fullname" . }}
  labels:
    {{- include "guacd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guacd.service.type }}
  ports:
    - port: 4822
      name: {{ .Chart.Name }}-guacd
      targetPort: {{ .Chart.Name }}-guacd
  selector:
    {{- include "guacd.selectorLabels" . | nindent 4 }}
