apiVersion: v1
kind: Service
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      name: web
      targetPort: web
  selector:
    {{- include "dashy.selectorLabels" . | nindent 4 }}
