apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cross-seed
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://vyrtualsynthese.github.io/selfhosted-helmcharts/'
      chart: cross-seed
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/cluster/helm/media-stack/cross-seed/values.yaml
    - repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
      targetRevision: develop
      ref: values
