apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: plex-config-volume
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-transcode-volume
          persistentVolumeClaim:
            claimName: plex-transcode
        - name: plex-data-volume
          persistentVolumeClaim:
            claimName: plex-data
        - name: plex-media-volume
          persistentVolumeClaim:
            claimName: plex-media-hdd
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: plex
              containerPort: 32400
          env:
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PLEX_CLAIM"
              valueFrom:
                secretKeyRef:
                  name: plex
                  key: plex_claim
            - name: "ADVERTISE_IP"
              value: "https://plex.home.ashudev.com/"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: plex-config-volume
              mountPath: /config
            - name: plex-transcode-volume
              mountPath: /transcode
            - name: plex-data-volume
              mountPath: /data
            - name: plex-media-volume
              mountPath: /media
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
