apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.plex.fullname" . }}-config
  labels:
  {{- include "nextcloud.plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  resources:
    requests:
      storage: 1Gi
