apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: "0,30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: qbittorrent-download-volume
              persistentVolumeClaim:
                claimName: pvc-nfs-qbittorrent-download-nfs-subdir-external-provisioner
            - name: qbit-manage-config-volume
              persistentVolumeClaim:
                claimName: pvc-nfs-qbittorrent-config-nfs-subdir-external-provisioner
            - name: qbit-manage-secrets
              secret:
                secretName: qbit-manage
                items:
                  - key: config.yml
                    path: config.yml
          initContainers:
            - name: init-qbit-manage-config
              image: busybox:1.35
              command: [ 'sh', '-c', "cp /secret/* /config" ]
              volumeMounts:
                - mountPath: /config
                  name: qbit-manage-config-volume
                - mountPath: /secret
                  name: qbit-manage-secrets
          containers:
            - name: {{ include "fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: "TZ"
                  value: "Europe/Paris"
                - name: "PUID"
                  value: "1100"
                - name: "PGID"
                  value: "1100"
                - name: "QBT_RUN"
                  value: "true"
                - name: "QBT_REM_ORPHANED"
                  value: "false"
                - name: "QBT_TAG_UPDATE"
                  value: "true"
                - name: "QBT_DRY_RUN"
                  value: "false"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: qbittorrent-download-volume
                  mountPath: /downloads
                - mountPath: /config
                  name: qbit-manage-config-volume
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - nas
