apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mc.fullname" . }}
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mc.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mc.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: minecraft-server-volume
          persistentVolumeClaim:
            claimName: minecraft-lh-2
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: OPS
              value: "vsynthese"
            - name: MAX_WORLD_SIZE
              value: "12500"
            - name: VERSION
              value: "1.21.1"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "FALSE"
            - name: MODE
              value: "survival"
            - name: PVP
              value: "TRUE"
            - name: SERVER_NAME
              value: "ashulab-1.19"
            - name: VIEW_DISTANCE
              value: "10"
            - name: MEMORY
              value: ""
            - name: TYPE
              value: "PAPER"
            - name: MAX_TICK_TIME
              value: "-1"
            #- name: ENABLE_JMX
            #  value: "true"
            #- name: JMX_HOST
            #  value: "0.0.0.0"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: JVM_XX_OPTS
              value: "-XX:MaxRAMPercentage=75"
            - name: STOP_SERVER_ANNOUNCE_DELAY
              value: "30"
            - name: ENABLE_ROLLING_LOGS
              value: "true"
            - name: MODS
              value: "https://dev.bukkit.org/projects/multiverse-core/files/3462546/download,https://dev.bukkit.org/projects/multiverse-netherportals/files/3687506/download,https://dev.bukkit.org/projects/multiverse-portals/files/3113114/download"
          ports:
            - name: mc
              containerPort: 25565
            - name: jmx
              containerPort: 7091
          startupProbe:
            tcpSocket:
               port: 25565
            failureThreshold: 10
            periodSeconds: 60
          livenessProbe:
            tcpSocket:
              port: 25565
            periodSeconds: 60
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: minecraft-server-volume
              mountPath: /data
        - name: {{ .Chart.Name }}-exporter
          securityContext:
                              {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
          env:
            - name: EXPORT_SERVERS
              value: "127.0.0.1"
          ports:
            - name: monitor
              containerPort: 8080
          args:
            - export-for-prometheus
          resources:
                              {{- toYaml .Values.resources | nindent 12 }}

      terminationGracePeriodSeconds: 600
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
