{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mc.fullname" . -}}
{{- $svcPort := .Values.service.clusterip.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-public
  labels:
    {{- include "mc.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - mc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: minecraft-server
          port: mc
{{- end }}
