storage:
  crossSeed:
    existingClaim: "cross-seed"
  torrents:
    existingClaim: "pvc-nfs-qbittorrent-config-nfs-subdir-external-provisioner"
    subPath: "qBittorrent/BT_backup"
conf:
  existingSecret: true
  secretName: "cross-seed"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 512Mi

nodeSelector:
  kubernetes.io/hostname: streaming
