apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overviewer.fullname" . }}
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "config" }}
  {{ . }}: |-
  {{ tpl ($files.AsConfig) $ | indent 2 }}
  {{- end }}
