apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "web.fullname" . }}-redirect-https
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
