authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: true
global:
  envFrom:
    - secretRef:
        name: authentik-env

server:
  ingress:
    enabled: true
    ingressClassName: ""
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "myresolver"
    hosts:
      - authentik.kub.home.ashudev.com
    paths:
      - /
    pathType: Prefix
    tls: []

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-postgresql-secrets"
  primary:
    persistence:
      existingClaim: "authentik-db"


redis:
  enabled: true
  master:
    persistence:
      enabled: false
