authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: true
global:
  envFrom:
    - secretRef:
        name: authentik-env
  addPrometheusAnnotations: false
  affinity:
    nodeAffinity:
      matchExpressions:
        - key: node-type
          operator: In
          values:
            - general

server:
  ingress:
    enabled: true
    ingressClassName: ""
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "kube-system-redirect-https@kubernetescrd,kube-system-discord@kubernetescrd"
      #traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "myresolver"
    hosts:
      - authentik.kub.home.ashudev.com
    paths:
      - /
    pathType: Prefix
    tls: []

postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-postgresql-secrets"
  primary:
    persistence:
      existingClaim: "authentik-db"



redis:
  enabled: true
  master:
    persistence:
      enabled: false
