apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9902
      name: exporter
      targetPort: exporter
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
