apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8181
      name: tautulli
      targetPort: tautulli
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
