kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lh-performance
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
#  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
#  backingImage: "bi-test"
#  backingImageDataSourceType: "download"
#  backingImageDataSourceParameters: '{"url": "https://backing-image-example.s3-region.amazonaws.com/test-backing-image"}'
#  backingImageChecksum: "SHA512 checksum of the backing image"
#  unmapMarkSnapChainRemoved: "ignored"
  diskSelector: "ssd"
#  nodeSelector: "storage,fast"
  recurringJobSelector: '[{"name":"no-backup", "isGroup":true}]'
#  nfsOptions: "soft,timeo=150,retrans=3"
