apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: web-ui
      port: 8265
      protocol: TCP
      targetPort: 8265
    - name: server
      port: 8266
      protocol: TCP
      targetPort: 8266
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
