apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  annotations:
#    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/autobrr/autobrr:^1.x
#    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
#    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
  name: autobrr
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://vyrtualsynthese.github.io/selfhosted-helmcharts/'
      chart: autobrr
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/cluster/helm/media-stack/autobrr/values.yaml
    - repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
      targetRevision: develop
      ref: values
