# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.containo.us/middleware_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-dashy
  namespace: dashy
spec:
  redirectRegex:
    regex: "^https?://kub\\.home\\.ashudev\\.com/(.*)"
    replacement: "https://dashy.ashudev.com/$1"
    permanent: true
