{{- if .Values.importer.ingress.enabled -}}
{{- $fullName := include "importer.fullname" . -}}
{{- if and .Values.app.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.importer.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.importer.ingress.annotations "kubernetes.io/ingress.class" .Values.app.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "importer.labels" . | nindent 4 }}
  {{- with .Values.importer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`firefly.importer.app.local`)
      kind: Rule
      services:
        - name: firefly-importer
          port: firefly-import
{{- end }}
