{{- if .Values.app.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- if and .Values.app.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.app.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.app.ingress.annotations "kubernetes.io/ingress.class" .Values.app.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-public
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`firefly.home.ashudev.com`)
      kind: Rule
      services:
        - name: firefly-app
          port: firefly-app
  tls:
    certResolver: myresolver
    options:
      name: firefly-app-tlsoption
{{- end }}
