apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: firefly-app-redirect-https
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
