apiVersion: v1
kind: Service
metadata:
  name: {{ include "importer.fullname" . }}
  labels:
    {{- include "importer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.importer.service.type }}
  ports:
    - port: 8080
      name: firefly-import
      targetPort: firefly-import
  selector:
    {{- include "importer.selectorLabels" . | nindent 4 }}
