apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://vyrtualsynthese.github.io/selfhosted-helmcharts/'
      chart: filebrowser
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/cluster/helm/media-stack/filebrowser/values.yaml
    - repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
      targetRevision: develop
      ref: values
