firefly-db:
  # if you set this to false it will not be installed
  enabled: true
  image:
    repository: postgres
    tag: 16.2-alpine3.18
    pullPolicy: IfNotPresent

  storage:
    class: ~
    accessModes: ReadWriteOnce
    dataSize: 1Gi
    # -- Use an existing PersistentVolumeClaim, overrides values above
    existingClaim:

  # environment variables
  configs:
    PGPASSWORD: "YOURDBPASSWORD"
    DBHOST: firefly-firefly-db
    DBPORT: "5432"
    DBNAME: firefly
    DBUSER: firefly
    TZ: Europe/Berlin

  backupSchedule: "0 3 * * *"

firefly-iii:
  # -- Set to false to not deploy Firefly III
  enabled: true

importer:
  # -- Set to false to not deploy the importer
  enabled: true

# https://github.com/firefly-iii/kubernetes/blob/main/charts/firefly-iii-stack/values.yaml
