apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5055
      name: seerr-webui
      targetPort: seerr-webui
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
