apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc.fullname" . }}
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25565
      nodePort: 31894
  selector:
    {{- include "mc.selectorLabels" . | nindent 4 }}
