# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.containo.us/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ashuvidz
  namespace: ashuvidz
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ashuvidz.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: security
          namespace: kube-system
      services:
        - name: ashuvidz-nginx
          port: 80
  tls:
    certResolver: myresolver
