apiVersion: v2
appVersion: 5.20.0
description: Install kube-state-metrics to generate and expose cluster-level metrics
home: https://prometheus-community.github.io/helm-charts
keywords:
- metric
- monitoring
- prometheus
- kubernetes
maintainers:
- email: tariq.ibrahim@mulesoft.com
  name: tariq1890
- email: manuel@rueg.eu
  name: mrueg
name: kube-state-metrics
sources:
- https://prometheus-community.github.io/helm-charts
type: application
version: 3.5.2
