apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.n8n.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.n8n.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.n8n.podSecurityContext | nindent 8 }}
      volumes:
        - name: n8n
          persistentVolumeClaim:
            claimName: "n8n"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.n8n.image.repository }}:{{ .Values.n8n.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.n8n.image.pullPolicy }}
          env:
            - name: "N8N_PORT"
              value: "5678"
            - name: "N8N_METRICS"
              value: "true"
            - name: "QUEUE_HEALTH_CHECK_ACTIVE"
              value: "true"
          ports:
            - containerPort: 5678
              name: "n8n"
          volumeMounts:
            - mountPath: "/home/node/.n8n"
              name: "n8n"
          resources:
            {{- toYaml .Values.n8n.resources | nindent 12 }}
      {{- with .Values.n8n.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.n8n.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.n8n.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
