apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: {{ .Values.n8n.service.type }}
  ports:
    - port: 5678
      name: n8n
      targetPort: n8n
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
