apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: webui
      targetPort: webui
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
