apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      name: identd
      targetPort: identd
    - port: 9000
      name: web
      targetPort: web
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
