apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: render-minecraft-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minecraft-server
  resources:
    requests:
      storage: 5Gi
