apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: 80
      name: inventree-lego
      targetPort: inventree-lego
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
