apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      volumes:
        - name: qbittorrent-config-volume
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-download-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-qbittorrent-download-nfs-subdir-external-provisioner
        - name: "dev-tun" # Needed for VPN
          hostPath:
            path: "/dev/net/tun"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-qbittorrent
          image: alpine:latest
          command: [ 'sh', '-c', "apk update && apk add unzip && wget https://github.com/WDaan/VueTorrent/releases/download/v0.19.1/vuetorrent.zip && unzip vuetorrent.zip && cp -r vuetorrent /config/ui" ]
          volumeMounts:
            - name: qbittorrent-config-volume
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}-vpn
          securityContext:
            capabilities: # Needed for VPN
              add:
                - NET_ADMIN
          image: "{{ .Values.vpnimage.repository }}:{{ .Values.vpnimage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vpnimage.pullPolicy }}
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: FIREWALL
              value: "off"
            - name: VPN_TYPE
              value: "wireguard"
            - name: VPN_ENDPOINT_IP
              value: "193.32.126.69"
            - name: WIREGUARD_PUBLIC_KEY
              value: "E/KjR7nlFouuRXh1pwGDr7iK2TAZ6c4K0LjjmA1A2Tc="
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: mullvad
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: mullvad
                  key: WIREGUARD_ADDRESSES
            #- name: "SERVER_HOSTNAMES"
            #  valueFrom:
            #    secretKeyRef:
            #      name: mullvad
            #      key: SERVER_HOSTNAMES
            #- name: "SERVER_COUNTRIES"
            #  value: "France"
            #- name: "SERVER_CITIES"
            #  value: "Paris"
            #- name: "OWNED_ONLY"
            #  value: "yes"
            #- name: "ISP"
            #  value: "31173"
            - name: "FIREWALL_VPN_INPUT_PORTS"
              valueFrom:
                secretKeyRef:
                  name: mullvad
                  key: FIREWALL_VPN_INPUT_PORTS
            - name: "FIREWALL_INPUT_PORTS"
              valueFrom:
                secretKeyRef:
                  name: mullvad
                  key: FIREWALL_INPUT_PORTS
            - name: "DOT"
              value: "off"
            - name: "DOT_IPV6"
              value: "off"
            - name: "DOT_PROVIDERS"
              value: "google"
            - name: "HEALTH_TARGET_ADDRESS"
              value: "cloudflare.com:443"
            - name: "BLOCK_MALICIOUS"
              value: "off"
            - name: "HEALTH_VPN_DURATION_INITIAL"
              value: "30s"
            - name: "HEALTH_VPN_DURATION_ADDITION"
              value: "10s"
            - name: "VPN_ENDPOINT_PORT"
              valueFrom:
                secretKeyRef:
                  name: mullvad
                  key: VPN_ENDPOINT_PORT
          volumeMounts:
            - name: "dev-tun"
              mountPath: "/dev/net/tun"
          resources:
            {{- toYaml .Values.vpnresources | nindent 12 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PUID"
              value: "0"
            - name: "PGID"
              value: "0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: qbittorrent-config-volume
              mountPath: /config
            - name: qbittorrent-download-volume
              mountPath: /downloads
          ports:
            - name: torrent-webui
              containerPort: 8080
            - name: torrent
              containerPort: 59565
              protocol: TCP
            - name: torrent-udp
              containerPort: 59565
              protocol: UDP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
