apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}-download-nfs
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Ti
