{
 "title": "Homelab Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu, instance))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)) / count(count(node_memory_MemTotal_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(((100 - ((node_filesystem_avail_bytes{fstype!=\"ext4\"} * 100) / (node_filesystem_size_bytes{fstype!=\"ext4\"})))))/ (count(count(node_filesystem_size_bytes) by (instance))))"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100) / count(count(node_memory_SwapTotal_bytes))"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)) / count(count(node_cpu_seconds_total{}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Ram Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"ext4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Used ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Ram Free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Used Swap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(node_network_up) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_thermal_zone_temp{zone=\"0\"}) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"\", container!~\"lb.*\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}}-limit"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_working_set_bytes{container!=\"\", container!~\"lb.*\"})",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum by (container) (kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "{{container}}-limit"
    }
   ]
  },
  {
   "title": "Network Traffic (Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_node) (rate(node_network_receive_bytes_total{device!~\"cni0|docker0|flannel.1|lo|veth.*\"}[5m]))",
     "legendFormat": "{{kubernetes_node}} Download"
    },
    {
     "expr": "sum by (kubernetes_node) (rate(node_network_transmit_bytes_total{device!~\"cni0|docker0|flannel.1|lo|veth.*\"}[5m]))",
     "legendFormat": "{{kubernetes_node}} Upload"
    }
   ]
  },
  {
   "title": "Network Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{interface!~\"cni0|docker0|flannel.1|lo|veth.*\",pod!~\".*prometheus.*\"}[5m]))",
     "legendFormat": "{{pod}} Receive"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{interface!~\"cni0|docker0|flannel.1|lo|veth.*\",pod!~\".*prometheus.*\"}[5m]))",
     "legendFormat": "{{pod}} Transmit"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device,kubernetes_node) (rate(node_disk_written_bytes_total{}[5m]))",
     "legendFormat": "{{kubernetes_node}} {{device}} Write"
    },
    {
     "expr": "sum by(device,kubernetes_node) (rate(node_disk_read_bytes_total{}[5m]))",
     "legendFormat": "{{kubernetes_node}} {{device}} Read"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=~\"/|/mnt.*\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=~\"/|/mnt.*\",fstype!=\"rootfs\"})",
     "legendFormat": "{{kubernetes_node}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(\r\n  100 *\r\n    sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"POD\"}) by (container)\r\n      /\r\n    sum(container_spec_memory_limit_bytes{image!=\"\", container_name!=\"POD\"} > 0) by (container)\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}