apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10999
      name: dst-1
      protocol: UDP
      nodePort: 31999
    - port: 11000
      name: dst-2
      protocol: UDP
      nodePort: 32000
    - port: 12346
      name: dst-3
      protocol: UDP
      nodePort: 32346
    - port: 12347
      name: dst-4
      protocol: UDP
      nodePort: 32347
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
