apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: qbittorrent-config-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-qbittorrent-config-nfs-subdir-external-provisioner
        - name: cross-seed-config-volume
          persistentVolumeClaim:
            claimName: cross-seed-config
        - name: cross-seed-volume
          persistentVolumeClaim:
            claimName: cross-seed
        - name: cross-seed-secrets
          secret:
            secretName: cross-seed
            items:
              - key: config
                path: config.js
      initContainers:
        - name: init-cross-seed-config
          image: busybox:1.35
          command: [ 'sh', '-c', "cp /secret/* /config" ]
          volumeMounts:
            - mountPath: /config
              name: cross-seed-config-volume
            - mountPath: /secret
              name: cross-seed-secrets
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cross-seed", "daemon"]
          ports:
            - name: cross-seed
              containerPort: 2468
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: qbittorrent-config-volume
              mountPath: /torrents
              subPath: qBittorrent/BT_backup
            - mountPath: /config
              name: cross-seed-config-volume
            - mountPath: /cross-seed
              name: cross-seed-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
