annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
apiVersion: v2
appVersion: 1.2.6
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
description: Admision controller to change the default gateway and DNS server of PODs
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/pod-gateway
icon: https://pod-gateway.org/icon
keywords:
- pod-gateway
kubeVersion: '>=1.16.0-0'
maintainers:
- email: git@angelnu.com
  name: angelnu
name: pod-gateway
sources:
- https://github.com/k8s-at-home/gateway-admision-controller
- https://github.com/k8s-at-home/pod-gateway
version: 5.4.2
