global:
  postgresql:
    auth:
      existingSecret: "postgres-secrets"

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 17.0.0-debian-12-r3

primary:
  resources: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - general
  updateStrategy:
    type: RollingUpdate
  persistence:
    existingClaim: "databases-postgres"

backup:
  enabled: true
  resources: {}
  cronjob:
    storage:
      existingClaim: "databases-postgres-backup"

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.15.0-debian-12-r44
  resources: {}
  serviceMonitor:
    enabled: true

