global:
  postgresql:
    auth:
      existingSecret: "postgres-secrets"

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.4.0-debian-12-r2

primary:
  resources:
    requests:
      cpu: 0.1
      memory: 1Gi
    limits:
      memory: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - general
  updateStrategy:
    type: RollingUpdate
  persistence:
    existingClaim: "databases-postgres1"

backup:
  enabled: true
  resources: {}
  cronjob:
    command:
      - /bin/bash
      - -c
      - PGPASSWORD="${PGPASSWORD:-$(< "$PGPASSWORD_FILE")}" pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file="${PGDUMP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump" && find "$PGDUMP_DIR" -maxdepth 1 -name "pg_dumpall-*.pgdump" -type f -printf "%T@ %p\n" | sort -nr | tail -n +31 | cut -d' ' -f2- | xargs -r rm --"
    storage:
      existingClaim: "databases-postgres-backup"

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.15.0-debian-12-r44
  resources: {}
  serviceMonitor:
    enabled: true
