apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: qbittorrent-download-volume
              persistentVolumeClaim:
                claimName: qbittorrent-download
            - name: qbit-manage-config-volume
              persistentVolumeClaim:
                claimName: qbit-manage-config-lh
            - name: qbit-manage-secrets
              secret:
                secretName: qbit-manage
                items:
                  - key: config.yml
                    path: config.yml
          initContainers:
            - name: init-nextcloud-nginx-config
              image: busybox:1.35
              command: [ 'sh', '-c', "cp /secret/* /config" ]
              volumeMounts:
                - mountPath: /config
                  name: qbit-manage-config-volume
                - mountPath: /secret
                  name: qbit-manage-secrets
          containers:
            - name: {{ include "fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: "TZ"
                  value: "Europe/Paris"
                - name: "PUID"
                  value: "0"
                - name: "PGID"
                  value: "0"
                - name: "QBT_RUN"
                  value: "true"
                - name: "QBT_REM_ORPHANED"
                  value: "true"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: qbittorrent-download-volume
                  mountPath: /downloads
                - mountPath: /config
                  name: qbit-manage-config-volume
          restartPolicy: OnFailure
