apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-smartctl
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
    targetRevision: develop
    path: cluster/helm/monitoring/prometheus-smartctl
