apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-node-xps13
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels-node-xps13" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels-node-xps13" . | nindent 8 }}
    spec:
      volumes:
        - name: tdarr-temp-volume
          persistentVolumeClaim:
            claimName: pvc-tdarr-cache
        - name: plex-media-volume
          persistentVolumeClaim:
            claimName: pvc-plex-media
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-node-xps13
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageNode.repository }}:{{ .Values.imageNode.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 8266 #PMS
              protocol: TCP
          env:
            - name: "serverIP"
              value: "tdarr"
            - name: "serverPort"
              value: "8266"
            - name: "webUIPort"
              value: "8265"
            - name: "nodeName"
              value: "AshuFlixNode-xps13"
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PUID"
              value: "0"
            - name: "PGID"
              value: "0"
            - name: "NVIDIA_DRIVER_CAPABILITIES"
              value: "compute,video,utility"
            - name: "NVIDIA_VISIBLE_DEVICES"
              value: "all"
          resources:
            {{- toYaml .Values.resourcesNodeXps13 | nindent 12 }}
          volumeMounts:
            - name: tdarr-temp-volume
              mountPath: /temp
            - name: plex-media-volume
              mountPath: /media
            - name: plex-media-volume
              mountPath: /media-hd
            - name: plex-media-volume
              mountPath: /media-sd
      {{- with .Values.nodeSelectorNodeXps13 }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
