apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: tdarr-server-volume
          persistentVolumeClaim:
            claimName: tdarr-server
        - name: tdarr-logs-volume
          persistentVolumeClaim:
            claimName: tdarr-logs
        - name: tdarr-temp-volume
          persistentVolumeClaim:
            claimName: tdarr-temp-nfs
        - name: plex-media-volume
          persistentVolumeClaim:
            claimName: plex-media-nfs

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web-ui
              containerPort: 8265
              protocol: TCP
            - name: server
              containerPort: 8266 #PMS
              protocol: TCP
          env:
            - name: "serverIP"
              value: "0.0.0.0"
            - name: "serverPort"
              value: "8266"
            - name: "webUIPort"
              value: "8265"
            - name: "internalNode"
              value: "false"
            - name: "inContainer"
              value: "true"
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PUID"
              value: "0"
            - name: "PGID"
              value: "0"
            - name: "NVIDIA_DRIVER_CAPABILITIES"
              value: "compute,video,utility"
            - name: "NVIDIA_VISIBLE_DEVICES"
              value: "all"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tdarr-server-volume
              mountPath: /app/server
            - name: tdarr-logs-volume
              mountPath: /app/logs
            - name: tdarr-temp-volume
              mountPath: /temp
            - name: plex-media-volume
              mountPath: /media
            - name: plex-media-volume
              mountPath: /media-hd
            - name: plex-media-volume
              mountPath: /media-sd
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
