- hosts: all
  remote_user: vronteix
  become: yes

  tasks:
    - name: install restic from apt
      apt:
        name: restic
        state: present

    - name: Update restic from sources
      ansible.builtin.command: sudo restic self-update

# Prepare Users and Folder for Slaves Nodes on Master Nodes

- hosts: backup_slave
  remote_user: vronteix
  become: yes

  tasks:
    - name: Create backup users for all slaves
      ansible.builtin.user:
        name: "{{ inventory_hostname }}"
        groups: admins
        state: present
        append: yes
        shell: /bin/bash

    - name: Create .ssh folder for all slaves
      ansible.builtin.file:
        path: "/home/{{ inventory_hostname }}/.ssh"
        state: directory
        owner: "{{ inventory_hostname }}"
        group: "{{ inventory_hostname }}"

    - name: Generate SSH Key for all slave machines
      community.crypto.openssh_keypair:
        path: "/home/{{ inventory_hostname }}/.ssh/id_rsa"
        owner: "{{ inventory_hostname }}"

    - name: Store SSH Keys on Runner Machine
      ansible.builtin.fetch:
        src: "/home/{{ inventory_hostname }}/.ssh/id_rsa.pub"
        dest: "{{ playbook_dir }}/keys/{{ inventory_hostname }}/"
        flat: yes

# Setup on Master Node

- hosts: backup_master
  remote_user: vronteix
  become: yes

  tasks:
    - name: Create backup folder of master
      ansible.builtin.file:
        path: /srv/backup/xps-13
        state: directory
        owner: root
        group: root
        mode: '0750'

    - name: Create users for all slave Nodes
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
      loop: "{{ query('inventory_hostnames', 'backup_slave') }}"

    - name: Create a backup folder for every slaves
      ansible.builtin.file:
        path: /srv/backup/{{ item }}
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0750'
      loop: "{{ query('inventory_hostnames', 'backup_slave') }}"

    - name: Copy Slave's SSH key to corresponding authorized Key file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/keys/{{ item }}/"
        dest: "/home/{{ item }}/.ssh/"
        owner: "{{ item }}"
        group: "{{ item }}"
      loop: "{{ query('inventory_hostnames', 'backup_slave') }}"

- hosts: all
  remote_user: vronteix
  become: yes

  tasks:
    - name: Import Restic passwords
      include_vars:
        file: restic_env.yaml
        name: restic_env

    - name: Set restic password as env variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        regexp: '^RESTIC_PASSWORD'
        line: 'RESTIC_PASSWORD="{{ restic_env[inventory_hostname].password }}"'

    - name: Set restic path as env variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        regexp: '^RESTIC_REPOSITORY'
        line: 'RESTIC_REPOSITORY="{{ restic_env[inventory_hostname].path }}"'

- hosts: backup_master
  remote_user: vronteix
  become: yes
  tasks:

    - name: Check if repo already configured
      ansible.builtin.command: sudo restic snapshots
      register: repoCheckReturn
      ignore_errors: yes

    - name: Setup Local Repository for Master Node Backup
      ansible.builtin.command: sudo restic init
      when: repoCheckReturn.rc != 0

    - name: Import backup script
      ansible.builtin.copy:
        src: "scripts/backup.sh"
        dest: "/home/vronteix/scripts/"
        owner: "vronteix"
        group: "vronteix"
        mode: '0550'

    # TODO: setup remote repo for child nodes

    # TODO: Copy bash script for automate backup

    # TODO: Create cron job with right permission

# Prepare Repository for master and child Nodes

# !!!! Write and test backup script for master
# push backup script to master
# configure cronjob to master backup script

# !!! Write backup script for slaves
# push backup script on slaves
# configure cronjob to master backup script
