- hosts: all
  remote_user: vronteix
  become: yes

  tasks:
    - name: create sudoers group
      ansible.builtin.group:
        name: admins
        state: present

    - name: Update and upgrade apt packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Create and add vronteix to admin group
      ansible.builtin.user:
        name: vronteix
        state: present
        groups: admins
        append: yes

    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^admins ALL=(ALL) NOPASSWD: ALL'
        line: '%admins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: vronteix
        state: present
        key: "{{ lookup('file', '/home/vyrtualsynthese/.ssh/homelab_rsa.pub') }}"

    - name: Disable root login over SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart sshd

    - name: Disable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

  # configure log rotate
  # Configure systemd journal logs size
