- hosts: all
  remote_user: vronteix
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Upgrade Restic
      ansible.builtin.command: restic self-update
      register: resticStdout
      changed_when:
        - resticStdout.stdout.find('is up to') == -1

- hosts: runner
  remote_user: vronteix
  become: yes

  tasks:
    - name: Upgrade docker compse if needed
      community.docker.docker_compose:
        pull: true
        project_src: /home/vronteix/dockers
