{{- if .Values.linkstack.ingress.enabled -}}
{{- $fullName := include "linkstack.fullname" . -}}
{{- $svcPort := .Values.linkstack.service.port -}}
{{- if and .Values.linkstack.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.linkstack.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.linkstack.ingress.annotations "kubernetes.io/ingress.class" .Values.linkstack.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-public
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
  {{- with .Values.linkstack.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`linkstack.kub.home.ashudev.com`)
      kind: Rule
      services:
        - name: linkstack
          port: linkstack
  tls:
    certResolver: myresolver
    options:
      name: {{ include "linkstack.fullname" . }}-tlsoption
{{- end }}
