apiVersion: v2
name: ashuvidz-website
description: Ashuvidz
type: application
version: 0.1.0
dependencies:
  - name: nginx
    version: 22.6.9
    repository: oci://registry-1.docker.io/bitnamicharts
