image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.1.1

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: dashy.kub.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 1m
    memory: 128Mi
  limits:
    memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - general
                - small

env:
  NODE_ENV: "production"
  PORT: "80"
  #HOST: ""
  #BASE_URL: ""
  #VUE_APP_DOMAIN: ""
  #INTEGRITY: ""
  # -- Set this to the name of a secret to load environment variables from. If defined, values in the secret will override values in configs
  existingSecret: ""

static:
  enabled: true
  existingSecret: "dashy-config"
  # Customize config.yaml https://github.com/Lissy93/dashy/blob/master/docs/configuring.md for more information.
  configMapContent: ""
