apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-nfs
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  source:
    repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
    targetRevision: develop
    path: cluster/helm/nfs/minio-nfs
