apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-qbittorrent-config
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-stack
  source:
    repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
    targetRevision: develop
    path: cluster/helm/nfs/nfs-qbittorrent-config
