apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 17871
      name: qbt-exporter
      targetPort: qbt-exporter
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
