apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: guacamole=guacamole/guacamole:^1.x, guacd=guacamole/guacd:^1.x, db=postgres:^15.x-0
    argocd-image-updater.argoproj.io/guacamole.helm.image-name: guacamole.image.repository
    argocd-image-updater.argoproj.io/guacamole.helm.image-tag: guacamole.image.tag
    argocd-image-updater.argoproj.io/guacd.helm.image-name: guacd.image.repository
    argocd-image-updater.argoproj.io/guacd.helm.image-tag: guacd.image.tag
    argocd-image-updater.argoproj.io/db.helm.image-name: db.image.repository
    argocd-image-updater.argoproj.io/db.helm.image-tag: db.image.tag
    argocd-image-updater.argoproj.io/db.allow-tags: 'regexp:^(0|[1-9]\d*)\.(0|[1-9]\d*)?-alpine.*'
  name: guacamole
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guacamole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
    targetRevision: develop
    path: cluster/helm/guacamole

