# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.containo.us/ingressroute_v1alpha1.json
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr
  namespace: {{ .Release.Namespace | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`huntarr.kub.local`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: security
          namespace: kube-system
      services:
        - name: huntarr
          port: 9705
  tls:
    certResolver: myresolver

