replicaCount: 1

image:
  repository: ghcr.io/gitroomhq/postiz-app
  pullPolicy: IfNotPresent
  tag: "v1.30.1-amd64"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  additionalPorts: []

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "kube-system-authentik@kubernetescrd,kube-system-security@kubernetescrd"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "myresolver"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: "postiz.kub.home.ashudev.com"
  hosts:
    - host: postiz.kub.home.ashudev.com
      paths:
        - path: /
          pathType: Prefix
          port: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  extraRules: []

resources: {}

extraContainers: []

extraVolumes:
  - name: uploads-volume
    persistentVolumeClaim:
      claimName: postiz-uploads
extraVolumeMounts:
  - name: uploads-volume
    mountPath: /uploads

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - general
                - small

# PostgreSQL configuration
postgresql:
  enabled: false

# Redis configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
    password: postiz-redis-password
  master:
    service:
      ports:
        redis: 6379

# Environment variables
env:
  MAIN_URL: "https://postiz.kub.home.ashudev.com"
  FRONTEND_URL: "https://postiz.kub.home.ashudev.com"
  NEXT_PUBLIC_BACKEND_URL: "https://postiz.kub.home.ashudev.com/api"
  BACKEND_INTERNAL_URL: "http://localhost:3000"
  UPLOAD_DIRECTORY: "/uploads"
  NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY: ""
  NX_ADD_PLUGINS: "false"
  IS_GENERAL: "true"
  STORAGE_PROVIDER: "local"
