apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: databases
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'registry-1.docker.io/bitnamicharts'
      path: postgresql
      chart: postgresql
      targetRevision: 15.5.19
      helm:
        valueFiles:
          - $values/cluster/helm/databases/postgres.yaml
    - repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
      targetRevision: develop
      ref: values
