apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2468
      name: cross-seed
      targetPort: cross-seed
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
