apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "nginx.prod.conf" }}
  {{ . }}: |-
  {{ tpl ($files.AsConfig) $ | indent 2 }}
  {{- end }}
