apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxy.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: inventree-lego-data
          persistentVolumeClaim:
            claimName: inventree-lego-data2
        - name: conf-cache-volume
          emptyDir: { }
        - name: inventree-lego-proxy-configmap
          configMap:
            name: {{ include "proxy.fullname" . }}
      {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-nextcloud-nginx-config
          image: busybox:1.35
          command: [ 'sh', '-c', "cp /config/nginx.prod.conf /cache" ]
          volumeMounts:
            - mountPath: /cache
              name: conf-cache-volume
            - mountPath: /config
              name: inventree-lego-proxy-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: inventree-lego
          volumeMounts:
            - name: inventree-lego-data
              mountPath: /var/www
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.prod.conf
              name: conf-cache-volume
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
