apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mc.fullname" . }}
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mc.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mc.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: minecraft-server-volume
          persistentVolumeClaim:
            claimName: minecraft-server
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EULA
              value: "TRUE"
            - name: WHITELIST
              value: "vsynthese,Tarrhen,PapeCaponche,Carabaf,JambonLeVrai,KaFeuk,LeGrandSimon,Ramzo1506,Ioni,Neka14"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: OPS
              value: "vsynthese"
            - name: MAX_WORLD_SIZE
              value: "12500"
            - name: VERSION
              value: "1.19"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "FALSE"
            - name: MODE
              value: "survival"
            - name: PVP
              value: "TRUE"
            - name: SERVER_NAME
              value: "ashulab-1.19"
            - name: VIEW_DISTANCE
              value: "10"
            - name: MEMORY
              value: ""
            - name: JVM_XX_OPTS
              value: "-XX:MaxRAMPercentage=75"
            - name: MAX_TICK_TIME
              value: "-1"
            - name: ENABLE_JMX
              value: "true"
            - name: JMX_HOST
              value: "0.0.0.0"
            - name: STOP_SERVER_ANNOUNCE_DELAY
              value: "30"
            - name: ENABLE_ROLLING_LOGS
              value: "true"
          ports:
            - name: mc
              containerPort: 25565
            - name: jmx
              containerPort: 7091
          startupProbe:
            tcpSocket:
               port: 25565
            failureThreshold: 5
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: minecraft-server-volume
              mountPath: /data
      terminationGracePeriodSeconds: 300
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
