apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mc.fullname" . }}
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mc.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mc.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: minecraft-server-volume
          persistentVolumeClaim:
            claimName: minecraft-server
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EULA
              value: "TRUE"
            - name: WHITELIST
              value: "vsynthese,Tarrhen,PapeCaponche,Carabaf,JambonLeVrai,KaFeuk,LeGrandSimon,Ramzo,Ramzo1506,Ioni,Ionni14,Neka14"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: OPS
              value: "vsynthese"
            - name: MAX_WORLD_SIZE
              value: "8000"
            - name: VERSION
              value: "1.18"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "FALSE"
            - name: MODE
              value: "survival"
            - name: PVP
              value: "TRUE"
            - name: SERVER_NAME
              value: "ashulab-1.18"
            - name: VIEW_DISTANCE
              value: "16"
            - name: INIT_MEMORY
              value: "512M"
            - name: MAX_MEMORY
              value: "6G"
            - name: ENABLE_AUTOPAUSE
              value: "TRUE"
            - name: MAX_TICK_TIME
              value: "-1"
            - name: AUTOPAUSE_TIMEOUT_EST
              value: "60"
            - name: AUTOPAUSE_TIMEOUT_INIT
              value: "60"
            - name: ENABLE_JMX
              value: "true"
            - name: JMX_HOST
              value: "0.0.0.0"
            - name: ENABLE_ROLLING_LOGS
              value: "true"
          ports:
            - name: mc
              containerPort: 25565
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: minecraft-server-volume
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
