apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mc.fullname" . }}
  labels:
  {{- include "mc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minecraft-server
  resources:
    requests:
      storage: 5Gi
