apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: plex-config-volume
          persistentVolumeClaim:
            claimName: plex-config
        - name: audio-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-audio-nfs-subdir-external-provisioner
        #- name: plex-transcode-volume
        #  persistentVolumeClaim:
        #    claimName: plex-transcode
        - name: plex-media-volume
          persistentVolumeClaim:
            claimName: pvc-plex-media
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: plex
              containerPort: 32400 #PMS
              protocol: TCP
            - containerPort: 32400
              name: plex-udp
              protocol: UDP
            - containerPort: 32469 #Plex DLNA
              name: plex-dlna
            - containerPort: 5353
              name: plex-discovery
              protocol: UDP
            - containerPort: 1900 #Plex DLNA
              name: plex-dlna-udp
              protocol: UDP
          env:
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PLEX_CLAIM"
              valueFrom:
                secretKeyRef:
                  name: plex
                  key: plex_claim
            - name: "ADVERTISE_IP"
              value: "https://plex.kub.home.ashudev.com:443"
            - name: "HOSTNAME"
              value: "plex"
            - name: "VERSION"
              value: "docker"
            - name: "ALLOWED_NETWORKS"
              value: "192.168.1.0/16,10.42.0.0/16"
            - name: "PUID"
              value: "1100"
            - name: "PGID"
              value: "1100"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: plex-config-volume
              mountPath: /config
            - name: plex-media-volume
              mountPath: /media
            - name: audio-volume
              mountPath: /audio
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
