apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}-media-nfs
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-hdd
  resources:
    requests:
      storage: 10Ti
