apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: gpu-operator
      repoURL: https://helm.ngc.nvidia.com/nvidia
      targetRevision: v24.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
