apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n8n
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: registry.hub.docker.com/n8nio/n8n:0.142.0
          env:
            - name: GENERIC_TIMEZONE
              value: "Europe/Paris"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_METRICS
              value: "true"
            - name: HEATZY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: heatzy
                  key: USERNAME
            - name: HEATZY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heatzy
                  key: PASSWORD
            - name: SWITCHBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: switchbot
                  key: SECRET
          ports:
            - name: web
              containerPort: 5678
          volumeMounts:
            - name: n8n
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n
          persistentVolumeClaim:
            claimName: n8n
