kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: n8n
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path