apiVersion: v1
kind: Service
metadata:
  name: {{ include "home.fullname" . }}
  labels:
    {{- include "home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: web
  selector:
    {{- include "home.selectorLabels" . | nindent 4 }}
