apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://docs.renovatebot.com/helm-charts'
      chart: renovate
      targetRevision: 37.274.0
      helm:
        valueFiles:
          - $values/cluster/helm/renovate/values.yaml
    - repoURL: 'https://github.com/vyrtualsynthese/homelab.git'
      targetRevision: develop
      ref: values
