apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-dashboard
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`prom.local`)
    kind: Rule
    services:
      - name: prometheus-server
        port: 80