{
 "title": "Pi k3s Simple Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "HOST", "query": "label_values(kubernetes_node)" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Node Load 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load5{kubernetes_node=~\"[[HOST]]\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{kubernetes_node=~\"[[HOST]]\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(node_network_up) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_thermal_zone_temp) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_duration_seconds_sum{kubernetes_io_hostname=~\"[[HOST]]\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{k3s_io_hostname}}"
    }
   ]
  },
  {
   "title": "TCP Established Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{kubernetes_node=~\"[[HOST]]\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Transmit Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"[[HOST]]\"}[5m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} IN"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"[[HOST]]\"}[5m])) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} OUT"
    }
   ]
  }
 ]
}