{
 "title": "Network Traffic",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "LocalIPs",
    "query": {
     "query": "label_values(ntm_bytes_total, src)"
    }
   },
   {
    "name": "Services",
    "query": {
     "query": "label_values(ntm_bytes_total, service)"
    }
   },
   {
    "name": "Protos",
    "query": {
     "query": "label_values(ntm_bytes_total, proto)"
    }
   },
   { "name": "ExcludedServers" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic (Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(node_network_receive_bytes_total{device=~\"enp3s0|enx1027f551348e|eth0\"}[5m]))",
     "legendFormat": "{{kubernetes_node}} Download"
    },
    {
     "expr": "sum by (kubernetes_node) (rate(node_network_transmit_bytes_total{device=~\"enp3s0|enx1027f551348e|eth0\"}[5m]))",
     "legendFormat": "{{kubernetes_node}} Upload"
    }
   ]
  },
  {
   "title": "Down by pod",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{interface=~\"enp3s0|enx1027f551348e|eth0\",pod!~\".*prometheus.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Up by Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{interface=~\"enp3s0|enx1027f551348e|eth0\",pod!~\".*prometheus.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Downloads (by Server)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(src) (increase(ntm_bytes_total{dst=~\"$LocalIPs\",src!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])))",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "title": "Uploads (by Server)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(dst) (increase(ntm_bytes_total{src=~\"$LocalIPs\",dst!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])))",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "$LocalIPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "LocalIPs",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(dst) (rate(ntm_bytes_total{dst=~\"$LocalIPs\",src!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
       "legendFormat": "{{ server }} (Down)"
      },
      {
       "expr": "sum by(src) (rate(ntm_bytes_total{src=~\"$LocalIPs\",dst!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
       "legendFormat": "{{ client }} (Up)"
      }
     ]
    }
   ]
  }
 ]
}