apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: "0,30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: plex-media-volume
              persistentVolumeClaim:
                claimName: pvc-plex-media
          containers:
            - name: {{ include "fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - "-c"
                - "sleep 60m"
              env:
                - name: "MOVIES_SRC_FOLDER_RELPATH"
                  value: "/data/movies"
                - name: "MOVIES_DST_FOLDER_RELPATH"
                  value: "/data/movies-hd"
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: plex-media-volume
                  mountPath: /data
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - nas
