init:
	ansible-galaxy collection install ansible.posix

setup-node:
	ansible-playbook playbooks/setup-node.yaml

upgrade-all:
	ansible-playbook playbooks/upgrade-all.yaml

backup-setup:
	ansible-playbook playbooks/backup-setup.yaml
