apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "proxy.fullname" . }}-security
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
