apiVersion: v1
kind: Service
metadata:
  name: {{ include "cache.fullname" . }}
  labels:
    {{- include "cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cache.service.type }}
  ports:
    - port: 6379
      name: inventree-lego-cache
      targetPort: redis
  selector:
    {{- include "cache.selectorLabels" . | nindent 4 }}
