apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextcloud.backup.fullname" . }}
  labels:
    {{- include "nextcloud.backup.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "backup.sh" }}
  {{ . }}: |-
  {{ tpl ($files.AsConfig) $ | indent 2 }}
  {{- end }}
