apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.cron.fullname" . }}
  labels:
    {{- include "nextcloud.cron.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.cron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.cron.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.cron.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: nextcloud-app-volume
          persistentVolumeClaim:
            claimName: nextcloud-app
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-nfs
      {{- with .Values.cron.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.cron.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cron.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-cron
          command: ["/cron.sh"]
          securityContext:
            {{- toYaml .Values.cron.securityContext | nindent 12 }}
          image: "{{ .Values.cron.image.repository }}:{{ .Values.cron.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          resources:
            {{- toYaml .Values.cron.resources | nindent 12 }}
          volumeMounts:
            - name: nextcloud-app-volume
              mountPath: /var/www/html
            - name: nextcloud-data-volume
              mountPath: /data
      {{- with .Values.cron.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
