apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.db.fullname" . }}
  labels:
    {{- include "nextcloud.db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.db.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: nextcloud-db-volume
          persistentVolumeClaim:
            claimName: nextcloud-postgres
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
{{/*      initContainers:*/}}
{{/*        - name: init-nextcloud-nginx-config*/}}
{{/*          image: postgres:14.2-alpine*/}}
{{/*          command: [ 'sh', '-c', "sleep 9000" ]*/}}
{{/*          volumeMounts:*/}}
{{/*            - name: nextcloud-db-volume*/}}
{{/*              mountPath: /var/lib/postgresql/data*/}}
{{/*              subPath: postgres-data*/}}
      containers:
        - name: {{ .Chart.Name }}-db
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
{{/*          livenessProbe:*/}}
{{/*            exec:*/}}
{{/*              command:*/}}
{{/*                - "pg_isready -d nextcloud-postgres -U nextcloud-postgres"*/}}
{{/*            failureThreshold: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*          startupProbe:*/}}
{{/*            exec:*/}}
{{/*              command:*/}}
{{/*                - "pg_isready -d nextcloud-postgres -U nextcloud-postgres"*/}}
{{/*            failureThreshold: 10*/}}
{{/*            periodSeconds: 10*/}}
          env:
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_PASSWORD
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_DB
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_USER
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: nextcloud-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
      terminationGracePeriodSeconds: 300
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
