apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.app.fullname" . }}
  labels:
    {{- include "nextcloud.app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.app.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-nfs
        - name: nextcloud-app-volume
          persistentVolumeClaim:
            claimName: nextcloud-app
        - name: conf-cache-volume
          emptyDir: {}
        - name: nextcloud-app-configmap
          configMap:
            name: {{ include "nextcloud.web.fullname" . }}
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: nextcloud-app
              containerPort: 9000
            - name: php-fpm-status
              containerPort: 9001
          env:
            - name: "PHP_UPLOAD_LIMIT"
              value: "100G"
            - name: "NEXTCLOUD_UPDATE"
              value: "0"
            - name: "POSTGRES_HOST"
              value: "nextcloud-db"
            - name: "REDIS_HOST"
              value: "nextcloud-redis"
            - name: "OVERWRITEPROTOCOL"
              value: "https"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_PASSWORD
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_DB
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_USER
            - name: NEXTCLOUD_DATA_DIR
              value: "/data"
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            - name: nextcloud-data-volume
              mountPath: /data
            - name: nextcloud-app-volume
              mountPath: /var/www/html
            - mountPath: /usr/local/etc/php/php.ini-production
              subPath: php.ini-production
              name: conf-cache-volume
            - mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
              name: conf-cache-volume
      initContainers:
        - name: init-nextcloud-nginx-config
          image: busybox:1.35
          command: [ 'sh', '-c', "cp /config/* /cache" ]
          volumeMounts:
            - mountPath: /cache
              name: conf-cache-volume
            - mountPath: /config
              name: nextcloud-app-configmap
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
