apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.db.fullname" . }}
  labels:
    {{- include "nextcloud.db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.db.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: nextcloud-db-volume
          persistentVolumeClaim:
            claimName: nextcloud-db
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-db
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_PASSWORD
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_DB
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_USER
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: nextcloud-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data

        - name: {{ .Chart.Name }}-db-backup
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.backup.image.repository }}:{{ .Values.db.backup.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.backup.image.pullPolicy }}
          env:
            - name: "POSTGRES_HOST"
              value: "localhost"
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_DB
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_USER
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: nextcloud-postgres
                  key: POSTGRES_PASSWORD
            - name: "BACKUP_DIR"
              value: "/var/lib/postgresql/data/backup"
            - name: "BACKUP_KEEP_DAYS"
              value: "7"
            - name: "BACKUP_KEEP_WEEKS"
              value: "4"
            - name: "BACKUP_KEEP_MONTHS"
              value: "1"
          resources:
            {{- toYaml .Values.db.backup.resources | nindent 12 }}
          volumeMounts:
            - name: nextcloud-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
      terminationGracePeriodSeconds: 300
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
