apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.db.fullname" . }}
  labels:
  {{- include "nextcloud.db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  resources:
    requests:
      storage: 1Gi
