apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.data.fullname" . }}-hdd
  labels:
  {{- include "nextcloud.app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  resources:
    requests:
      storage: 4Ti
