apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.redis.fullname" . }}
  labels:
    {{- include "nextcloud.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    {{- include "nextcloud.redis.selectorLabels" . | nindent 4 }}
