apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: readarr-config-volume
          persistentVolumeClaim:
            claimName: readarr-config
        - name: qbittorrent-download-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-qbittorrent-download-nfs-subdir-external-provisioner
        - name: books-volume
          persistentVolumeClaim:
            claimName: pvc-books-media-nfs-subdir-external-provisioner
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: readarr-webui
              containerPort: 8787
          env:
            - name: "TZ"
              value: "Europe/Paris"
            - name: "PUID"
              value: "1100"
            - name: "PGID"
              value: "1100"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: books-volume
              mountPath: /books
            - name: qbittorrent-download-volume
              mountPath: /downloads
            - name: readarr-config-volume
              mountPath: /config

        - name: {{ .Chart.Name }}-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.exportarr.image.repository }}:{{ .Values.exportarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.exportarr.image.pullPolicy }}
          ports:
            - name: exporter
              containerPort: 9707
          env:
            - name: "PORT"
              value: "9707"
            - name: "URL"
              value: "http://{{ .Chart.Name }}:8787"
            - name: "APIKEY"
              valueFrom:
                secretKeyRef:
                  name: readarr
                  key: secret
          args:
            - readarr
          resources:
            {{- toYaml .Values.exportarr.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
