apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-nfs
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: books-nfs
  resources:
    requests:
      storage: 1Ti
