apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: discord
spec:
  headers:
    accessControlAllowMethods:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginListRegex:
      - "https://discord\\.com.*"
    accessControlMaxAge: 100
    addVaryHeader: true
