apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: minio-data0-volume
          hostPath:
            path: /mnt/hdd0/minio
            type: Directory
        - name: minio-data1-volume
          hostPath:
            path: /mnt/hdd1/minio
            type: Directory
        - name: minio-data2-volume
          hostPath:
            path: /mnt/hdd2/minio
            type: Directory
        - name: minio-data3-volume
          hostPath:
            path: /mnt/hdd3/minio
            type: Directory
        - name: minio-data4-volume
          hostPath:
            path: /mnt/hdd4/minio
            type: Directory
        - name: minio-data5-volume
          hostPath:
            path: /mnt/hdd5/minio
            type: Directory
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          ports:
            - name: minio-api
              containerPort: 9000
            - name: minio-webui
              containerPort: 9090
          env:
            - name: "MINIO_ROOT_USER"
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_USER
            - name: "MINIO_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_PASSWORD
            - name: "MINIO_VOLUMES"
              value: "/data-{0...5}"
            - name: "MINIO_PROMETHEUS_URL"
              value: "http://prometheus-server.monitoring.svc.cluster.local"
            - name: "MINIO_PROMETHEUS_JOB_ID"
              value: "kubernetes-pods"
            - name: "MINIO_PROMETHEUS_AUTH_TYPE"
              value: "public"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: minio-data0-volume
              mountPath: /data-0
            - name: minio-data1-volume
              mountPath: /data-1
            - name: minio-data2-volume
              mountPath: /data-2
            - name: minio-data3-volume
              mountPath: /data-3
            - name: minio-data4-volume
              mountPath: /data-4
            - name: minio-data5-volume
              mountPath: /data-5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
