apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-sync
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: minio-sync-config
          secret:
            secretName: minio-sync
            items:
              - key: config.json
                path: config.json
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-minio-config
          image: busybox:1.35
          command: [ 'sh', '-c', "cp /secret/* /config" ]
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /secret
              name: minio-sync-config
      containers:
        - name: {{ .Chart.Name }}-sync-rbp0-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-rbp0/rbp0backup s3-rbp0-backup/ashudev-homelab-rbp0-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
        - name: {{ .Chart.Name }}-sync-rbp1-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-rbp1/rbp1backup s3-rbp1-backup/ashudev-homelab-rbp1-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
        - name: {{ .Chart.Name }}-sync-longhorn-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-longhorn/longhorn s3-longhorn-backup/ashudev-homelab-longhorn-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
        - name: {{ .Chart.Name }}-sync-nextcloud-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-nextcloud/nextcloudbackup s3-nextcloud-backup/ashudev-homelab-nextcloud-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
        - name: {{ .Chart.Name }}-sync-minio-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-nas/nasbackup s3-nas-backup/ashudev-homelab-nas-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
        - name: {{ .Chart.Name }}-sync-syncthing-backup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sync.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - mc mirror --watch --overwrite --remove minio-syncthing/syncthingbackup s3-syncthing-backup/ashudev-homelab-syncthing-backup --debug
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.mc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
