apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      name: minio-webui
      targetPort: minio-webui
    - port: 9000
      name: minio-api
      targetPort: minio-api
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
