apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8787
      name: readarr-webui
      targetPort: readarr-webui
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
