apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.fullname" . }}-db
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: ghostfolio-db-volume
          persistentVolumeClaim:
            claimName: ghostfolio-db
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-db
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: db
              containerPort: 5432
          envFrom:
            - secretRef:
                name: ghostfolio
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - "-c"
                  - "su - postgres -c '/var/lib/postgresql/data/pg_ctl stop -D /var/lib/postgresql/data'"
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: ghostfolio-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: ghostfolio-data

        - name: {{ .Chart.Name }}-db-backup
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.backup.image.repository }}:{{ .Values.db.backup.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.backup.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: ghostfolio
          env:
            - name: "POSTGRES_HOST"
              value: "localhost"
            - name: "BACKUP_DIR"
              value: "/var/lib/postgresql/data/backup"
            - name: "BACKUP_KEEP_DAYS"
              value: "7"
            - name: "BACKUP_KEEP_WEEKS"
              value: "4"
            - name: "BACKUP_KEEP_MONTHS"
              value: "1"
          resources:
            {{- toYaml .Values.db.backup.resources | nindent 12 }}
          volumeMounts:
            - name: ghostfolio-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: ghostfolio-data
      terminationGracePeriodSeconds: 600
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
