apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: 6379
      name: redis
      targetPort: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
