apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}-db
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: 5432
      name: db
      targetPort: db
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
