apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}-vpn
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain
  resources:
    requests:
      storage: 10Mi
