apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextcloud.app.fullname" . }}
  labels:
    {{- include "nextcloud.app.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "php.ini-production" "www.conf" }}
  {{ . }}: |-
  {{ tpl ($files.AsConfig) $ | indent 2 }}
  {{- end }}
