{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "nextcloud.web.fullname" . -}}
{{- $svcPort := .Values.web.service.port -}}
{{- if and .Values.web.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.web.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.web.ingress.annotations "kubernetes.io/ingress.class" .Values.web.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-public
  labels:
    {{- include "nextcloud.web.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nextcloud.kub.home.ashudev.com`)
      kind: Rule
      services:
        - name: nextcloud-web
          port: web
  tls:
    certResolver: myresolver
    options:
      name: nextcloud-web-tlsoption
{{- end }}
