apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-web-redirect-https
  labels:
    {{- include "nextcloud.web.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
