apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.data.fullname" . }}
  labels:
  {{- include "nextcloud.app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 8Ti
