
{{- $fullName := include "grafana.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-public
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.home.ashudev.com`)
      kind: Rule
      services:
        - name: grafana
          port: service
  tls:
    certResolver: myresolver
    options:
      name: grafana-tlsoption

