
{{- $fullName := include "grafana.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.app.local`)
      kind: Rule
      services:
        - name: grafana
          port: service

