apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "overviewer.fullname" . }}-cron
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
spec:
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: minecraft-server-volume
              persistentVolumeClaim:
                claimName: minecraft-lh
            - name: render-minecraft-server-volume
              persistentVolumeClaim:
                claimName: render-minecraft
            - name: conf-cache-volume
              emptyDir: {}
            - name: overviewer-configmap
              configMap:
                name: {{ include "overviewer.fullname" . }}
          initContainers:
            - name: init-nextcloud-nginx-config
              image: busybox:1.35
              command: [ 'sh', '-c', "cp /config/config /cache" ]
              volumeMounts:
                - mountPath: /cache
                  name: conf-cache-volume
                - mountPath: /config
                  name: overviewer-configmap
          containers:
            - name: overviewer-cron
              image: registry.hub.docker.com/vyrtualsynthese/overviewer:multi-arch-latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 100Mi
              volumeMounts:
                - name: minecraft-server-volume
                  mountPath: /app/overviewer/src/Minecraft-Overviewer-master/world
                - name: render-minecraft-server-volume
                  mountPath: /app/overviewer/src/Minecraft-Overviewer-master/render
                - mountPath: /app/overviewer/src/Minecraft-Overviewer-master/config
                  subPath: config
                  name: conf-cache-volume
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
