apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "overviewer.fullname" . }}-redirect-https
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
