apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: render-minecraft-server
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minecraft-server
  resources:
    requests:
      storage: 10Gi
