apiVersion: v1
kind: Service
metadata:
  name: {{ include "overviewer.fullname" . }}
  labels:
    {{- include "overviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      name: web
      targetPort: web
  selector:
    {{- include "overviewer.selectorLabels" . | nindent 4 }}
