apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alpine
    spec:
      volumes:
        - name: data1
          persistentVolumeClaim:
            claimName: qbittorrent-config
      containers:
        - image: alpine:latest
          command:
            - /bin/sh
            - "-c"
            - "sleep 60m"
          imagePullPolicy: IfNotPresent
          name: alpine
          volumeMounts:
            - name: data1
              mountPath: /data1
