apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: filebrowser-db-volume
          persistentVolumeClaim:
            claimName: filebrowser-db
        - name: filebrowser-config-volume
          persistentVolumeClaim:
            claimName: filebrowser-config
        - name: stash-volume
          persistentVolumeClaim:
            claimName: pvc-stash-nfs-nfs-stash
        - name: audio-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-audio-nfs-subdir-external-provisioner
        - name: qbittorrent-download-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-qbittorrent-download-nfs-subdir-external-provisioner
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: filebrowser
              containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: FB_CONFIG
              value: "/config/settings.json"
            - name: "FB_DATABASE"
              value: "/database/filebrowser.db"
          volumeMounts:
            - name: filebrowser-db-volume
              mountPath: /database
            - name: filebrowser-config-volume
              mountPath: /config
            - name: stash-volume
              mountPath: /srv/various
            - name: audio-volume
              mountPath: /srv/audio
            - name: qbittorrent-download-volume
              mountPath: /srv/torrent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
