apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}-media-hdd
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: retain
  resources:
    requests:
      storage: 10Ti
