apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      name: calibre-gui
      targetPort: calibre-gui
    - port: 8081
      name: calibre-webui
      targetPort: calibre-webui
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
