name: homelab image builder
on:
  push:
    branches:
      - main
jobs:
  Home-Lab-Builder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ home, dashy ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get file changes
        id: changed-files-specific
        uses: tj-actions/changed-files@v10
        with:
          files: |
            apps/${{ matrix.project }}

      - name: Set up QEMU
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: steps.changed-files-specific.outputs.any_changed == 'true'

      - name: Set up Docker Buildx
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to DockerHub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: vyrtualsynthese/${{ matrix.project }}
          flavor: |
            latest=true
            prefix=multi-arch-,onlatest=true
            suffix=
          tags: |
            type=sha,enable=true,priority=100,prefix=multi-arch-,suffix=,format=short

      - name: Build and push
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./apps/${{ matrix.project }}/
          file: ./apps/${{ matrix.project }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          progress: plain