name: homelab image builder
on:
  push:
    branches:
      - main
jobs:
  Home-Lab-Builder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ dashy, overviewer ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vyrtualsynthese/${{ matrix.project }}
          flavor: |
            latest=true
            prefix=multi-arch-,onlatest=true
            suffix=
          tags: |
            type=sha,enable=true,priority=100,prefix=multi-arch-,suffix=,format=short

      - name: Build
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          context: ./apps/${{ matrix.project }}/
          file: ./apps/${{ matrix.project }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./apps/${{ matrix.project }}/
          file: ./apps/${{ matrix.project }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
