name: homelab image builder
on:
  push:
    branches:
      - main
jobs:
  Home-Lab-Builder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ home ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=4 ${{ github.sha }})

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: vyrtualsynthese/home

      - name: Build and push
        env:
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./apps/home/
          file: ./apps/home/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: multi-arch:$SHORTSHA,multi-arch:latest