apiVersion: v2
name: pgadmin
description: pgadmin
type: application
version: 0.1.0
dependencies:
  - name: pgadmin
    version: 1.50.0 # Version du chart open-source que tu veux utiliser
    repository: https://vyrtualsynthese.github.io/rowanruseler/
